### ISSUE TITLE
MGIS/MusaBase use case and/or Trait selector Brapp

### ISSUE THREAD

**Issue by guignonv** [plantbreeding/BrAPI-Manuscript2#1]
We got a use case between MGIS and MusaBase using BrAPI. It illustrate a link between a gene bank database and a breeding database. It is possible to fetch available breeding from MusaBase on any MGIS ITC accession page.
Ex.: https://www.crop-diversity.org/mgis/accession/01BEL084253
![image](https://github.com/plantbreeding/BrAPI-Manuscript2/assets/7290244/fe80e226-7e5d-456c-915e-6a78f10f3412)
which dynamically fetches info using BrAPI and gives:
![image](https://github.com/plantbreeding/BrAPI-Manuscript2/assets/7290244/bcab3c37-e038-4353-87dd-97abd225bcdc)

I know there us also the reverse: on MusaBase, some accession information are updated using MGIS BrAPI endpoint. However, I don't know if it is still in use since Guillaume Bauchet is not behind anymore... it should be checked and confirmed from the Cornell side.

Regarding the Trait selector, what could be convenient for the paper? It should be possible for me to put online the new interface, hopefully by the end of the year... But what could be "sexy" to show? What could interest most users? Because there are many (useful) ways to use it. Do we have a deadline for submitting? Would we have place for a figure?

**Comment by mrouard** [comment]
hello, I am also convinced that those 2 elements would be relevant for the paper, ideally combined if both MGIS and Breedbase are using the trait selector.

**Comment by BrapiCoordinatorSelby** [comment]
Agreed, perhaps you could work with @MFlores2021 to write a couple of paragraphs for this. Can steal some pieces from the post-sabbatical report as a starting point

**Comment by mrouard** [comment]
This is an excellent suggestion. thanks Peter.
