### ISSUE TITLE
Florilège use case

### ISSUE THREAD

**Issue by aliceboizet** [plantbreeding/BrAPI-Manuscript2#18]
Here is a first draft for Florilège use case:

FLORILÈGE (Gateway to French Plant Genetic Resources)  

Designed primarily for the general public, Florilège provides access to all French plant biological resources centers. Its interface allows individuals to browse available plant accessions and gives them the possibility to order them. The listed accessions originate from 19 resources centers and concern around fifty plant species.
Florilège retrieves accession information from different BrAPI-compliant systems such as OLGA, an internal accessions management system, or FAIDARE. Leveraging the BrAPI implementation of these systems ensures standardized data retrieval from multiple sources, making the integration of new data sources that implement BrAPI an effortless process. The implementation of BrAPI is a prerequisite for the integration of any new database in Florilège.
Florilège is developed in Drupal 10, and uses xnttbrapi module (to easily connect to BrAPI compliant external databases)

**Comment by BrapiCoordinatorSelby** [comment]
added content to the manuscript
