### ISSUE TITLE
Data visualization section

### ISSUE THREAD

**Issue by sebastian-raubach** [plantbreeding/BrAPI-Manuscript2#2]
I think it'd be good to also add a success story section for data visualization tools like Flapjack, Helium and Tassel.

Do you want us to contribute to the manuscript directly or via these issues initially?
If directly, pull requests?

**Comment by BrapiCoordinatorSelby** [comment]
Visualization section is a great idea 👍 
Contributions can be made however you are most comfortable. Issues, pull requests, or send me an email with your thoughts. I'll sort it all out.

**Comment by BrapiCoordinatorSelby** [comment]
I'm going to talk more about contributions during the upcoming hackathon (Oct 2023). If you can't make the live session, there will be a recording that will hopefully answer most questions.

**Comment by sebastian-raubach** [comment]
https://github.com/plantbreeding/BrAPI-Manuscript2/pull/3
