### ISSUE TITLE
Which journal should we submit this to?

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [plantbreeding/BrAPI-Manuscript2#5]
Looking for Journal suggestions

We are targeting plant scientists and breeders, showcasing the tools and use cases they can use that BrAPI has enabled.

**Comment by cpommier** [comment]
# New Phytologist [IF 7.961]
https://nph.onlinelibrary.wiley.com/hub/journal/14698137/about/author-guidelines
-> Rather high selection pressure. high impact toward plant researchers/biologists. Very opened to FAIR (MIAPPE and PHIS paper there)

# Plant Phenomics [IF6.961] 
More specialised
Opened to biologists, tools, sensors and data science. 
IPPN link

# The Plant journal [IF6.417]
https://onlinelibrary.wiley.com/journal/1365313x

**Comment by BrapiCoordinatorSelby** [comment]
Discussed during the hackathon and advisory board meeting. 
We are going to try for Nature: Scientific Data
https://www.nature.com/sdata/publish/for-authors#other-formats

> The ‘Article’ format can be used to present original reports on systems and techniques related to data sharing in repositories. Common topics include data policies, repositories, standards, ontologies, workflows or another other areas related to the mechanics or culture of data sharing within this use case. These should include an Introduction followed by sections headed Results, Discussion, Methods. All Article submissions should include code and data availability statements. Guidance on writing a data availability statement can be [found here](https://www.springernature.com/gp/authors/research-data-policy/data-availability-statements/12330880). The Methods should be followed by References, Acknowledgements and a Competing interests statement.
