### ISSUE TITLE
DArTView Contribution

### ISSUE THREAD

**Issue by jndmose** [plantbreeding/BrAPI-Manuscript2#50]
Hi Peter,
See more updated content below from the one I sent through email.

DArTView is a desktop application for marker data curation via metadata filtering. DArTView enables genotype variant data visualization and users can easily identify trends or correlations within their data using the tool. Its primary goal is to overcome tedious manual calculation of marker data through common spreadsheet applications like excel. 
Users are able to upload marker data from csv files, however in addition to this it's newly BrAPI compatible and can use a BrAPI compatible server as an input data source.

Initially developed by Diversity Arrays Technology (DArT), the tool is gaining popularity within the breeding community, especially in Africa. Our future releases will focus on making it fully compatible to BrAPI (BraPP), making it accessible to more breeders and researchers in the region. Via development of web version of the application we will also open it to collaboration with other interested partners who would like to integrate it as part of their pipelines.

**Comment by BrapiCoordinatorSelby** [comment]
@jndmose Thanks, this looks good. 

Can I ask for one more sentence? You say DArTView is BrAPI compatible, but you don't talk about why that is useful for users. 

Some possible reasons to consider: Is it to avoid manual file manipulation? Is it to have more efficient filtering/slicing of larger datasets through the API? Is there a specific use case or system you needed to connect to which was easier to do with BrAPI? Does BrAPI provide a consistent use of a data standard that was missing before? 

I just need one, maybe two, sentences explaining why BrAPI is useful.

I'll get the rest of this added to the manuscript. I might edit it a little for grammar and make sure it flows with the rest of the text

**Comment by jndmose** [comment]
Hi Peter,
Usefulness of BrAPI to the tool:

BrAPI provides a consistent data standard across databases that are BrAPi compatible. DArTView compatibility with BrAPI also ensures easy integration with other tools and pipelines that would use DArTView for marker filtering and exploration.
